"""Edited team and participation

Revision ID: 0cd4401b3685
Revises: afc115a74c97
Create Date: 2026-05-03 10:04:47.582278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd4401b3685'
down_revision: Union[str, Sequence[str], None] = 'afc115a74c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tournament_participation_ibfk_1'), 'tournament_participation', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_participation', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_participation', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_participation_ibfk_1'), 'tournament_participation', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
