"""Mark Aligned with Contract

Revision ID: 3ddf542cd136
Revises: fbb3fbd072f7
Create Date: 2026-05-10 12:34:42.436873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ddf542cd136'
down_revision: Union[str, Sequence[str], None] = 'fbb3fbd072f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('marks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('submission_start', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('tasks', 'max_mark',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'name')
    op.drop_constraint(op.f('tournament_participation_ibfk_1'), 'tournament_participation', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_participation', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('judge_code'), table_name='tournaments')
    op.drop_column('tournaments', 'judge_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('judge_code', mysql.VARCHAR(length=6), nullable=False))
    op.create_index(op.f('judge_code'), 'tournaments', ['judge_code'], unique=True)
    op.drop_constraint(None, 'tournament_participation', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_participation_ibfk_1'), 'tournament_participation', 'teams', ['team_id'], ['id'])
    op.add_column('tasks', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('tasks', 'max_mark',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'submission_start')
    op.drop_column('tasks', 'title')
    op.drop_column('marks', 'created_at')
    op.drop_column('marks', 'comment')
    # ### end Alembic commands ###
