"""Max_mark Fix

Revision ID: 701ab0588c80
Revises: 2456198f42dd
Create Date: 2026-05-03 11:27:36.969140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '701ab0588c80'
down_revision: Union[str, Sequence[str], None] = '2456198f42dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'max_mark',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'max_mark',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
