"""Code Revisions

Revision ID: c1230d3d72e8
Revises: cc2b51e82723
Create Date: 2026-04-22 22:34:17.904928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1230d3d72e8'
down_revision: Union[str, Sequence[str], None] = 'cc2b51e82723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('is_captain = FALSE OR team_id IS NOT NULL', name='ck_captain_req_team'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'registration', 'active', 'finished', 'cancelled')", name='ck_tournament_status'),
    sa.CheckConstraint('max_teams > 0', name='ck_tournament_max_teams_positive'),
    sa.CheckConstraint('start_date > registration_deadline', name='ck_tournament_start_after_registration_deadline'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('max_mark', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_participation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=36), nullable=False),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('registered', 'approved', 'disqualified', 'finished', 'withdrawn')", name='ck_tournament_participation_status'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'tournament_id', name='uq_tournament_participation'),
    sa.UniqueConstraint('tournament_id', 'place', name='uq_leaderboard_tournament_place')
    )
    op.create_table('solutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_user_role',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_participation_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.CheckConstraint("(role = 'participant' AND tournament_participation_id IS NOT NULL) OR (role != 'participant' AND tournament_participation_id IS NULL)", name='ck_tur_participant_needs_team'),
    sa.CheckConstraint("role IN ('participant', 'judge', 'organizer')", name='ck_tur_role'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['tournament_participation_id'], ['tournament_participation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id', name='uq_tur_user_tournament')
    )
    op.create_table('marks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.String(length=36), nullable=False),
    sa.Column('solution_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['tournament_user_role.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'judge_id', name='uq_mark_solution_judge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('tournament_user_role')
    op.drop_table('solutions')
    op.drop_table('tournament_participation')
    op.drop_table('tasks')
    op.drop_table('tournaments')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
