"""Updated User

Revision ID: c60c9fc27e5b
Revises: 9f8eca86f06e
Create Date: 2026-04-29 14:36:13.839405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60c9fc27e5b'
down_revision: Union[str, Sequence[str], None] = '9f8eca86f06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('join_code', sa.String(length=6), nullable=False))
    op.create_unique_constraint(None, 'teams', ['join_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'join_code')
    # ### end Alembic commands ###
