"""Model Fixes

Revision ID: cc2b51e82723
Revises: 
Create Date: 2026-04-16 13:59:55.676421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc2b51e82723'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('is_captain = FALSE OR team_id IS NOT NULL', name='ck_captain_req_team'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'registration', 'active', 'finished', 'cancelled')", name='ck_tournament_status'),
    sa.CheckConstraint('max_teams > 0', name='ck_tournament_max_teams_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_leaderboard_tournament_team')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('max_mark', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_tournament',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('registered', 'approved', 'disqualified', 'finished', 'withdrawn')", name='ck_team_tournament_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'tournament_id', name='uq_team_tournament')
    )
    op.create_table('solutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('file', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_user_role',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_tournament_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.CheckConstraint("(role = 'participant' AND team_tournament_id IS NOT NULL) OR (role != 'participant' AND team_tournament_id IS NULL)", name='ck_tur_participant_needs_team'),
    sa.CheckConstraint("role IN ('participant', 'judge', 'organizer')", name='ck_tur_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id', name='uq_tur_user_tournament')
    )
    op.create_table('marks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.String(length=36), nullable=False),
    sa.Column('solution_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'judge_id', name='uq_mark_solution_judge')
    )

    op.create_foreign_key('fk_users_team_id_teams', 'users', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk_tournaments_created_by_users', 'tournaments', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_leaderboard_tournament_id_tournaments', 'leaderboard', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key('fk_leaderboard_team_id_teams', 'leaderboard', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk_tasks_tournament_id_tournaments', 'tasks', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key('fk_team_tournament_team_id_teams', 'team_tournament', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk_team_tournament_tournament_id_tournaments', 'team_tournament', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key('fk_solutions_task_id_tasks', 'solutions', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('fk_solutions_team_id_teams', 'solutions', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk_tur_team_tournament_id', 'tournament_user_role', 'team_tournament', ['team_tournament_id'], ['id'])
    op.create_foreign_key('fk_tur_tournament_id', 'tournament_user_role', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key('fk_tur_user_id', 'tournament_user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_marks_judge_id_users', 'marks', 'users', ['judge_id'], ['id'])
    op.create_foreign_key('fk_marks_solution_id_solutions', 'marks', 'solutions', ['solution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_marks_solution_id_solutions', 'marks', type_='foreignkey')
    op.drop_constraint('fk_marks_judge_id_users', 'marks', type_='foreignkey')
    op.drop_constraint('fk_tur_user_id', 'tournament_user_role', type_='foreignkey')
    op.drop_constraint('fk_tur_tournament_id', 'tournament_user_role', type_='foreignkey')
    op.drop_constraint('fk_tur_team_tournament_id', 'tournament_user_role', type_='foreignkey')
    op.drop_constraint('fk_solutions_team_id_teams', 'solutions', type_='foreignkey')
    op.drop_constraint('fk_solutions_task_id_tasks', 'solutions', type_='foreignkey')
    op.drop_constraint('fk_team_tournament_tournament_id_tournaments', 'team_tournament', type_='foreignkey')
    op.drop_constraint('fk_team_tournament_team_id_teams', 'team_tournament', type_='foreignkey')
    op.drop_constraint('fk_tasks_tournament_id_tournaments', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_leaderboard_team_id_teams', 'leaderboard', type_='foreignkey')
    op.drop_constraint('fk_leaderboard_tournament_id_tournaments', 'leaderboard', type_='foreignkey')
    op.drop_constraint('fk_tournaments_created_by_users', 'tournaments', type_='foreignkey')
    op.drop_constraint('fk_users_team_id_teams', 'users', type_='foreignkey')

    op.drop_table('marks')
    op.drop_table('tournament_user_role')
    op.drop_table('solutions')
    op.drop_table('team_tournament')
    op.drop_table('tasks')
    op.drop_table('leaderboard')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('users')
    # ### end Alembic commands ###
