"""Task Edits

Revision ID: e34ebddce19c
Revises: 0cd4401b3685
Create Date: 2026-05-03 10:51:25.427180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e34ebddce19c'
down_revision: Union[str, Sequence[str], None] = 'c60c9fc27e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('submission_start', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('tasks', 'name')
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'description')
    op.add_column('tasks', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('tasks', 'submission_start')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
