"""Judge_code added

Revision ID: fbb3fbd072f7
Revises: 701ab0588c80
Create Date: 2026-05-08 15:54:54.254633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbb3fbd072f7'
down_revision: Union[str, Sequence[str], None] = '701ab0588c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('tasks', 'max_mark',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'submission_start')
    op.drop_column('tasks', 'title')
    op.add_column('tournaments', sa.Column('judge_code', sa.String(length=6), nullable=False))
    op.create_unique_constraint(None, 'tournaments', ['judge_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='unique')
    op.drop_column('tournaments', 'judge_code')
    op.add_column('tasks', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('tasks', sa.Column('submission_start', mysql.DATETIME(), nullable=False))
    op.alter_column('tasks', 'max_mark',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###